package view;

import presenter.ICrearSalida;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Paquete;
import model.Unidad;
import presenter.Agencia;

/**
 *
 * @author josdan
 */
public class CrearSalida extends javax.swing.JFrame implements ICrearSalida {
    
    private Agencia presentador;
    private DefaultComboBoxModel paquetesModel;
    private HashMap<String, String> paquetes;
    private DefaultComboBoxModel unidadesModel;
    private HashMap<String, Integer> unidades;
    
    public CrearSalida() {
        initComponents();
        this.setTitle("CREAR SALIDA");
        this.paquetesModel = new DefaultComboBoxModel();
        this.unidadesModel = new DefaultComboBoxModel();
        this.presentador = new Agencia(this);
        this.paquetes = new HashMap<>();
        this.unidades = new HashMap<>();
        this.presentador.comenzarNuevaSalida();
        //poner la ventana al centro
        this.setLocationRelativeTo(null);
        //inicializar combobox paquetes y unidades
        //this.cmbPaquetes.setModel(new DefaultComboBoxModel(new String[]{}));
        //this.cmbUnidades.setModel(new DefaultComboBoxModel(new String[]{}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearSalida = new javax.swing.JPanel();
        lblNuevaSalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbPaquetes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbUnidades = new javax.swing.JComboBox<>();
        panelFecha = new javax.swing.JPanel();
        calendario = new com.toedter.calendar.JCalendar();
        lblCupos = new javax.swing.JLabel();
        txtCupos = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        lblNuevaSalida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNuevaSalida.setText("CREAR NUEVA SALIDA");

        jLabel1.setText("PAQUETE");

        cmbPaquetes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaquetesItemStateChanged(evt);
            }
        });

        jLabel2.setText("UNIDAD");

        cmbUnidades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUnidadesItemStateChanged(evt);
            }
        });

        panelFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "FECHA"));

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblCupos.setText("CUPOS");

        btnCancelar.setText("CANCELAR");

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearSalidaLayout = new javax.swing.GroupLayout(panelCrearSalida);
        panelCrearSalida.setLayout(panelCrearSalidaLayout);
        panelCrearSalidaLayout.setHorizontalGroup(
            panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearSalidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNuevaSalida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCrearSalidaLayout.createSequentialGroup()
                .addGroup(panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearSalidaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(panelCrearSalidaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblCupos)))
                .addGap(43, 43, 43)
                .addGroup(panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPaquetes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbUnidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCrearSalidaLayout.createSequentialGroup()
                        .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addComponent(txtCupos))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearSalidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmar)
                .addGap(9, 9, 9))
        );
        panelCrearSalidaLayout.setVerticalGroup(
            panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearSalidaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNuevaSalida)
                .addGap(46, 46, 46)
                .addGroup(panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCupos)
                    .addComponent(txtCupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelCrearSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPaquetesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaquetesItemStateChanged
        if (!evt.getItem().toString().equals("---Seleccionar Paquete---")) {
            this.presentador.seleccionarPaquetes(this.paquetes.get(evt.getItem().toString()));
            System.out.println(evt.getItem().toString());
        }
    }//GEN-LAST:event_cmbPaquetesItemStateChanged

    private void cmbUnidadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUnidadesItemStateChanged
        if (!evt.getItem().toString().equals("---Seleccionar Unidad---")) {
            int unidad = this.unidades.get(evt.getItem().toString()).intValue();
            this.presentador.seleccionarUnidad(unidad);
            System.out.println(unidad);
        }
    }//GEN-LAST:event_cmbUnidadesItemStateChanged

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (this.validarCampos()) {
            this.presentador.ingresarFecha(this.obtenerFecha());
            this.presentador.ingresarCupo(this.obtenerCupos());
            this.presentador.confirmarSalida();
        } else {
            JOptionPane.showMessageDialog(this,
                    "COMPLETE LOS CAMPOS OBLIGATORIOS",
                    "MENSAJE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed
    
    @Override
    public void cargarPaquetes(ArrayList<Paquete> paquetes) {
        this.paquetesModel.addElement("---Seleccionar Paquete---");
        for (Paquete p : paquetes) {
            this.paquetesModel.addElement(p.getNombre());
            this.paquetes.put(p.getNombre(), p.getCodPaquete());
        }
        this.cmbPaquetes.setModel(paquetesModel);
    }
    
    @Override
    public String obtenerPaqueteSeleccionado() {
        return this.cmbPaquetes.getSelectedItem().toString();
    }
    
    @Override
    public void cargarUnidades(ArrayList<Unidad> unidades) {
        this.unidadesModel.removeAllElements();
        this.unidadesModel.addElement("---Seleccionar Unidad---");
        for (Unidad u : unidades) {
            String element = u.getNroUnidad() + ", " + u.getMarca() + ", " + u.getTipo();
            this.unidadesModel.addElement(element);
            this.unidades.put(element, u.getNroUnidad());
        }
        this.cmbUnidades.setModel(this.unidadesModel);
    }
    
    @Override
    public String obtenerUnidadSeleccionado() {
        return this.cmbUnidades.getSelectedItem().toString();
    }
    
    @Override
    public Date obtenerFecha() {
        int day = this.calendario.getDayChooser().getDay();
        int month = this.calendario.getMonthChooser().getMonth();
        int year = this.calendario.getYearChooser().getYear();
        
        return new Date(day, month, year);
    }
    
    @Override
    public int obtenerCupos() {
        return Integer.parseInt(this.txtCupos.getText());
    }
    
    @Override
    public void mostrarAlerta(String msj, String tipo) {
        if (tipo.equals("ADVERTENCIA")) {
            JOptionPane.showMessageDialog(this, msj, "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        if (tipo.equals("ERROR")) {
            JOptionPane.showMessageDialog(this, msj, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        if (tipo.equals("INFO")) {
            JOptionPane.showMessageDialog(this, msj, "INFO", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public boolean validarCampos() {
        if (!this.cmbPaquetes.getSelectedItem().toString().equals("---Seleccionar Paquete---")
                && !this.cmbUnidades.getSelectedItem().toString().equals("---Seleccionar Unidad---")
                && !this.txtCupos.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox<String> cmbPaquetes;
    private javax.swing.JComboBox<String> cmbUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCupos;
    private javax.swing.JLabel lblNuevaSalida;
    private javax.swing.JPanel panelCrearSalida;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JTextField txtCupos;
    // End of variables declaration//GEN-END:variables

}
