/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import model.Butaca;
import model.Paquete;
import model.Salida;
import presenter.CrearReservaPresenter;
import presenter.ICrearReserva;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class CrearReserva extends javax.swing.JFrame implements ICrearReserva {

    private CrearReservaPresenter presentador;
    private DefaultComboBoxModel paquetesModel;
    private HashMap<String, String> paquetes;
    private DefaultComboBoxModel salidasModel;
    private HashMap<String, String> salidas;

    /**
     * Creates new form CrearReserva
     */
    public CrearReserva() {
        initComponents();
        this.paquetesModel = new DefaultComboBoxModel();
        this.paquetes = new HashMap<>();
        this.salidasModel = new DefaultComboBoxModel();
        this.salidas = new HashMap<>();
        this.presentador = new CrearReservaPresenter(this);
        this.presentador.crearReserva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelReserva = new javax.swing.JPanel();
        lblCrearNuevaReserva = new javax.swing.JLabel();
        lblPaquete = new javax.swing.JLabel();
        cmbPaquetes = new javax.swing.JComboBox<>();
        lblSalida = new javax.swing.JLabel();
        cmbSalidas = new javax.swing.JComboBox<>();
        panelButacas = new javax.swing.JPanel();
        butaca1 = new javax.swing.JCheckBox();
        butaca2 = new javax.swing.JCheckBox();
        butaca3 = new javax.swing.JCheckBox();
        butaca4 = new javax.swing.JCheckBox();
        butaca5 = new javax.swing.JCheckBox();
        butaca6 = new javax.swing.JCheckBox();
        butaca7 = new javax.swing.JCheckBox();
        butaca8 = new javax.swing.JCheckBox();
        butaca9 = new javax.swing.JCheckBox();
        butaca10 = new javax.swing.JCheckBox();
        butaca11 = new javax.swing.JCheckBox();
        butaca12 = new javax.swing.JCheckBox();
        butaca13 = new javax.swing.JCheckBox();
        butaca14 = new javax.swing.JCheckBox();
        butaca15 = new javax.swing.JCheckBox();
        butaca16 = new javax.swing.JCheckBox();
        butaca17 = new javax.swing.JCheckBox();
        butaca18 = new javax.swing.JCheckBox();
        butaca19 = new javax.swing.JCheckBox();
        butaca20 = new javax.swing.JCheckBox();
        butaca21 = new javax.swing.JCheckBox();
        butaca22 = new javax.swing.JCheckBox();
        butaca23 = new javax.swing.JCheckBox();
        butaca24 = new javax.swing.JCheckBox();
        butaca25 = new javax.swing.JCheckBox();
        butaca26 = new javax.swing.JCheckBox();
        butaca27 = new javax.swing.JCheckBox();
        butaca28 = new javax.swing.JCheckBox();
        butaca29 = new javax.swing.JCheckBox();
        butaca30 = new javax.swing.JCheckBox();
        butaca31 = new javax.swing.JCheckBox();
        butaca32 = new javax.swing.JCheckBox();
        butaca33 = new javax.swing.JCheckBox();
        butaca34 = new javax.swing.JCheckBox();
        butaca35 = new javax.swing.JCheckBox();
        butaca36 = new javax.swing.JCheckBox();
        butaca37 = new javax.swing.JCheckBox();
        butaca38 = new javax.swing.JCheckBox();
        butaca39 = new javax.swing.JCheckBox();
        butaca40 = new javax.swing.JCheckBox();
        butaca41 = new javax.swing.JCheckBox();
        butaca42 = new javax.swing.JCheckBox();
        butaca43 = new javax.swing.JCheckBox();
        butaca44 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtDniCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        btnConfirmarReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        lblCrearNuevaReserva.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCrearNuevaReserva.setText("CREAR NUEVA RESERVA");

        lblPaquete.setText("PAQUETE");

        cmbPaquetes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaquetesItemStateChanged(evt);
            }
        });

        lblSalida.setText("SALIDA");

        cmbSalidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSalidasItemStateChanged(evt);
            }
        });

        panelButacas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Butacas"));
        panelButacas.setLayout(new java.awt.GridBagLayout());

        butaca1.setText("1");
        panelButacas.add(butaca1, new java.awt.GridBagConstraints());

        butaca2.setText("2");
        panelButacas.add(butaca2, new java.awt.GridBagConstraints());

        butaca3.setText("3");
        panelButacas.add(butaca3, new java.awt.GridBagConstraints());

        butaca4.setText("4");
        panelButacas.add(butaca4, new java.awt.GridBagConstraints());

        butaca5.setText("5");
        panelButacas.add(butaca5, new java.awt.GridBagConstraints());

        butaca6.setText("6");
        panelButacas.add(butaca6, new java.awt.GridBagConstraints());

        butaca7.setText("7");
        panelButacas.add(butaca7, new java.awt.GridBagConstraints());

        butaca8.setText("8");
        panelButacas.add(butaca8, new java.awt.GridBagConstraints());

        butaca9.setText("9");
        panelButacas.add(butaca9, new java.awt.GridBagConstraints());

        butaca10.setText("10");
        panelButacas.add(butaca10, new java.awt.GridBagConstraints());

        butaca11.setText("11");
        panelButacas.add(butaca11, new java.awt.GridBagConstraints());

        butaca12.setText("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca12, gridBagConstraints);

        butaca13.setText("13");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca13, gridBagConstraints);

        butaca14.setText("14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca14, gridBagConstraints);

        butaca15.setText("15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca15, gridBagConstraints);

        butaca16.setText("16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca16, gridBagConstraints);

        butaca17.setText("17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        panelButacas.add(butaca17, gridBagConstraints);

        butaca18.setText("18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca18, gridBagConstraints);

        butaca19.setText("19");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca19, gridBagConstraints);

        butaca20.setText("20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca20, gridBagConstraints);

        butaca21.setText("21");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca21, gridBagConstraints);

        butaca22.setText("22");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        panelButacas.add(butaca22, gridBagConstraints);

        butaca23.setText("23");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca23, gridBagConstraints);

        butaca24.setText("24");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca24, gridBagConstraints);

        butaca25.setText("25");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca25, gridBagConstraints);

        butaca26.setText("26");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca26, gridBagConstraints);

        butaca27.setText("27");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca27, gridBagConstraints);

        butaca28.setText("28");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca28, gridBagConstraints);

        butaca29.setText("29");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca29, gridBagConstraints);

        butaca30.setText("30");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca30, gridBagConstraints);

        butaca31.setText("31");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca31, gridBagConstraints);

        butaca32.setText("32");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca32, gridBagConstraints);

        butaca33.setText("33");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        panelButacas.add(butaca33, gridBagConstraints);

        butaca34.setText("34");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca34, gridBagConstraints);

        butaca35.setText("35");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca35, gridBagConstraints);

        butaca36.setText("36");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca36, gridBagConstraints);

        butaca37.setText("37");
        butaca37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaca37ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca37, gridBagConstraints);

        butaca38.setText("38");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca38, gridBagConstraints);

        butaca39.setText("39");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca39, gridBagConstraints);

        butaca40.setText("40");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca40, gridBagConstraints);

        butaca41.setText("41");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca41, gridBagConstraints);

        butaca42.setText("42");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca42, gridBagConstraints);

        butaca43.setText("43");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca43, gridBagConstraints);

        butaca44.setText("44");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        panelButacas.add(butaca44, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente"));

        jLabel1.setText("NOMBRE");

        jLabel2.setText("DNI");

        jLabel3.setText("TELEFONO");

        jLabel4.setText("CORREO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDniCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                            .addComponent(txtNombreCliente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnConfirmarReserva.setText("CONFIRMAR");

        btnCancelarReserva.setText("CANCELAR");

        javax.swing.GroupLayout panelReservaLayout = new javax.swing.GroupLayout(panelReserva);
        panelReserva.setLayout(panelReservaLayout);
        panelReservaLayout.setHorizontalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservaLayout.createSequentialGroup()
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelReservaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelarReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmarReserva))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelReservaLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(lblCrearNuevaReserva)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelReservaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReservaLayout.createSequentialGroup()
                                .addComponent(lblSalida)
                                .addGap(49, 49, 49)
                                .addComponent(cmbSalidas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelReservaLayout.createSequentialGroup()
                                .addComponent(lblPaquete)
                                .addGap(37, 37, 37)
                                .addComponent(cmbPaquetes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panelButacas, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        panelReservaLayout.setVerticalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCrearNuevaReserva)
                .addGap(36, 36, 36)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaquete)
                    .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalida)
                    .addComponent(cmbSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(panelButacas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarReserva)
                    .addComponent(btnCancelarReserva)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaca37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaca37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaca37ActionPerformed

    private void cmbPaquetesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaquetesItemStateChanged
        if (!evt.getItem().toString().equals("---Seleccionar Paquete---")) {
            this.presentador.seleccionarPaquetesReserva(this.obtenerPaqueteSeleccionado());
            System.out.println(evt.getItem().toString());
        }
    }//GEN-LAST:event_cmbPaquetesItemStateChanged

    private void cmbSalidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSalidasItemStateChanged
        if (!evt.getItem().toString().equals("---Seleccionar Salida---")) {
            this.presentador.seleccionarSalida(this.obtenerSalidaSeleccionada());
            System.out.println(evt.getItem().toString());
        }
    }//GEN-LAST:event_cmbSalidasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearReserva().setVisible(true);
            }
        });
    }

    @Override
    public void cargarPaquetes(ArrayList<Paquete> paquetes) {
        this.paquetesModel.addElement("---Seleccionar Paquete---");
        for (Paquete p : paquetes) {
            this.paquetesModel.addElement(p.getNombre());
            this.paquetes.put(p.getNombre(), p.getCodPaquete());
        }
        this.cmbPaquetes.setModel(paquetesModel);
    }

    @Override
    public String obtenerPaqueteSeleccionado() {
        return this.paquetes.get(this.cmbPaquetes.getSelectedItem().toString());
    }

    @Override
    public void cargarSalidas(ArrayList<Salida> salidas) {
        this.salidasModel.removeAllElements();
        this.salidasModel.addElement("---Seleccionar Salida---");
        for (Salida salida : salidas) {
            this.salidasModel.addElement(
                    String.valueOf(salida.getFecha().getDay())
                    + "/"
                    + String.valueOf(salida.getFecha().getMonth())
                    + "/"
                    + String.valueOf(salida.getFecha().getYear() + 1900)
            );
            this.salidas.put(salida.getFecha().toString(), salida.getCodSalida());
        }
        this.cmbSalidas.setModel(salidasModel);
    }

    @Override
    public String obtenerSalidaSeleccionada() {
        return this.salidas.get(this.cmbSalidas.getSelectedItem().toString());
    }

    @Override
    public void cargarButacas(ArrayList<Butaca> butacas) {
        for (Butaca butaca : butacas) {
            switch (butaca.getNroButaca()) {
                case 1:
                    this.butaca1.setSelected(true);
                    this.butaca1.setEnabled(false);
                    break;
                case 2:
                    this.butaca2.setSelected(true);
                    this.butaca2.setEnabled(false);
                    break;
                case 3:
                    this.butaca3.setSelected(true);
                    this.butaca3.setEnabled(false);
                    break;
                case 4:
                    this.butaca4.setSelected(true);
                    this.butaca4.setEnabled(false);
                    break;
                case 5:
                    this.butaca5.setSelected(true);
                    this.butaca5.setEnabled(false);
                    break;
                case 6:
                    this.butaca6.setSelected(true);
                    this.butaca6.setEnabled(false);
                    break;
                case 7:
                    this.butaca7.setSelected(true);
                    this.butaca7.setEnabled(false);
                    break;
                case 8:
                    this.butaca8.setSelected(true);
                    this.butaca8.setEnabled(false);
                    break;
                case 9:
                    this.butaca9.setSelected(true);
                    this.butaca9.setEnabled(false);
                    break;
                case 10:
                    this.butaca10.setSelected(true);
                    this.butaca10.setEnabled(false);
                    break;
                case 11:
                    this.butaca11.setSelected(true);
                    this.butaca11.setEnabled(false);
                    break;
                case 12:
                    this.butaca12.setSelected(true);
                    this.butaca12.setEnabled(false);
                    break;
                case 13:
                    this.butaca13.setSelected(true);
                    this.butaca13.setEnabled(false);
                    break;
                case 14:
                    this.butaca14.setSelected(true);
                    this.butaca14.setEnabled(false);
                    break;
                case 15:
                    this.butaca15.setSelected(true);
                    this.butaca15.setEnabled(false);
                    break;
                case 16:
                    this.butaca16.setSelected(true);
                    this.butaca16.setEnabled(false);
                    break;
                case 17:
                    this.butaca17.setSelected(true);
                    this.butaca17.setEnabled(false);
                    break;
                case 18:
                    this.butaca18.setSelected(true);
                    this.butaca18.setEnabled(false);
                    break;
                case 19:
                    this.butaca19.setSelected(true);
                    this.butaca19.setEnabled(false);
                    break;
                case 20:
                    this.butaca20.setSelected(true);
                    this.butaca20.setEnabled(false);
                    break;
                case 21:
                    this.butaca21.setSelected(true);
                    this.butaca21.setEnabled(false);
                    break;
                case 22:
                    this.butaca22.setSelected(true);
                    this.butaca22.setEnabled(false);
                    break;
                case 23:
                    this.butaca23.setSelected(true);
                    this.butaca23.setEnabled(false);
                    break;
                case 24:
                    this.butaca24.setSelected(true);
                    this.butaca24.setEnabled(false);
                    break;
                case 25:
                    this.butaca25.setSelected(true);
                    this.butaca25.setEnabled(false);
                    break;
                case 26:
                    this.butaca26.setSelected(true);
                    this.butaca26.setEnabled(false);
                    break;
                case 27:
                    this.butaca27.setSelected(true);
                    this.butaca27.setEnabled(false);
                    break;
                case 28:
                    this.butaca28.setSelected(true);
                    this.butaca28.setEnabled(false);
                    break;
                case 29:
                    this.butaca29.setSelected(true);
                    this.butaca29.setEnabled(false);
                    break;
                case 30:
                    this.butaca30.setSelected(true);
                    this.butaca30.setEnabled(false);
                    break;
                case 31:
                    this.butaca31.setSelected(true);
                    this.butaca31.setEnabled(false);
                    break;
                case 32:
                    this.butaca32.setSelected(true);
                    this.butaca32.setEnabled(false);
                    break;
                case 33:
                    this.butaca33.setSelected(true);
                    this.butaca33.setEnabled(false);
                    break;
                case 34:
                    this.butaca34.setSelected(true);
                    this.butaca34.setEnabled(false);
                    break;
                case 35:
                    this.butaca35.setSelected(true);
                    this.butaca35.setEnabled(false);
                    break;
                case 36:
                    this.butaca36.setSelected(true);
                    this.butaca36.setEnabled(false);
                    break;
                case 37:
                    this.butaca37.setSelected(true);
                    this.butaca37.setEnabled(false);
                    break;
                case 38:
                    this.butaca38.setSelected(true);
                    this.butaca38.setEnabled(false);
                    break;
                case 39:
                    this.butaca39.setSelected(true);
                    this.butaca39.setEnabled(false);
                    break;
                case 40:
                    this.butaca40.setSelected(true);
                    this.butaca40.setEnabled(false);
                    break;
                case 41:
                    this.butaca41.setSelected(true);
                    this.butaca41.setEnabled(false);
                    break;
                case 42:
                    this.butaca42.setSelected(true);
                    this.butaca42.setEnabled(false);
                    break;
                case 43:
                    this.butaca43.setSelected(true);
                    this.butaca43.setEnabled(false);
                    break;
                case 44:
                    this.butaca44.setSelected(true);
                    this.butaca44.setEnabled(false);
                    break;
            }
        }
    }

    @Override
    public String obtenerNombre() {
        return this.txtNombreCliente.getText();
    }

    @Override
    public long obtenerDni() {
        return Long.parseLong(this.txtDniCliente.getText());
    }

    @Override
    public String obtenerTelefono() {
        return this.txtTelefonoCliente.getText();
    }

    @Override
    public String obtenerCorreo() {
        return this.txtCorreoCliente.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnConfirmarReserva;
    private javax.swing.JCheckBox butaca1;
    private javax.swing.JCheckBox butaca10;
    private javax.swing.JCheckBox butaca11;
    private javax.swing.JCheckBox butaca12;
    private javax.swing.JCheckBox butaca13;
    private javax.swing.JCheckBox butaca14;
    private javax.swing.JCheckBox butaca15;
    private javax.swing.JCheckBox butaca16;
    private javax.swing.JCheckBox butaca17;
    private javax.swing.JCheckBox butaca18;
    private javax.swing.JCheckBox butaca19;
    private javax.swing.JCheckBox butaca2;
    private javax.swing.JCheckBox butaca20;
    private javax.swing.JCheckBox butaca21;
    private javax.swing.JCheckBox butaca22;
    private javax.swing.JCheckBox butaca23;
    private javax.swing.JCheckBox butaca24;
    private javax.swing.JCheckBox butaca25;
    private javax.swing.JCheckBox butaca26;
    private javax.swing.JCheckBox butaca27;
    private javax.swing.JCheckBox butaca28;
    private javax.swing.JCheckBox butaca29;
    private javax.swing.JCheckBox butaca3;
    private javax.swing.JCheckBox butaca30;
    private javax.swing.JCheckBox butaca31;
    private javax.swing.JCheckBox butaca32;
    private javax.swing.JCheckBox butaca33;
    private javax.swing.JCheckBox butaca34;
    private javax.swing.JCheckBox butaca35;
    private javax.swing.JCheckBox butaca36;
    private javax.swing.JCheckBox butaca37;
    private javax.swing.JCheckBox butaca38;
    private javax.swing.JCheckBox butaca39;
    private javax.swing.JCheckBox butaca4;
    private javax.swing.JCheckBox butaca40;
    private javax.swing.JCheckBox butaca41;
    private javax.swing.JCheckBox butaca42;
    private javax.swing.JCheckBox butaca43;
    private javax.swing.JCheckBox butaca44;
    private javax.swing.JCheckBox butaca5;
    private javax.swing.JCheckBox butaca6;
    private javax.swing.JCheckBox butaca7;
    private javax.swing.JCheckBox butaca8;
    private javax.swing.JCheckBox butaca9;
    private javax.swing.JComboBox<String> cmbPaquetes;
    private javax.swing.JComboBox<String> cmbSalidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCrearNuevaReserva;
    private javax.swing.JLabel lblPaquete;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JPanel panelButacas;
    private javax.swing.JPanel panelReserva;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables

}
